# The device (i.e. your inverter) to read from.
# Use: /dev/ttyS0 if you have a serial device,
#      /dev/ttyUSB0 if a USB<>Serial,
#      /dev/hidraw0 if you're connecting via the USB port on the inverter.
#
# You can also connect to a serial port on a remote device. For example, my inverter is connected as
# /dev/ttyMOD3 to Wirenboard controller on 192.168.1.55.
# Wirenboard:   ser2net -d -C "2012:raw:0:/dev/ttyMOD3:2400 8DATABITS NONE 1STOPBIT"
# Local PC:     socat pty,link=/tmp/ttyNET0 tcp:192.168.1.55:2012
# Port 2012 is arbitrary here and can be changed as you wish.
device=/dev/hidraw0

# The name or your inverter. The inverter will appear in Home Assistant under that name.
device_name=Small_6kw_Inverter

# Inverter's manufacturer. Can be arbitrary. Will be shown in Home Assistant.
device_manufacturer=Knox

# Inverter's model. Can be arbitrary. Will be shown in Home Assistant.
device_model=Krypton

# MQTT broker IP address.
mqtt_server=core-mosquitto

# MQTT broker port. 1883 is the default port for mo
mqtt_port=1883

# Password/username credentials to connect to the broker.
# Comment them out or leave empty if your broker doesn't require user/password.
mqtt_username=mqtt_user
mqtt_password=123456

# Discovery prefix: https://www.home-assistant.io/integrations/mqtt/#discovery-messages
# Home Assistant uses "homeassistant" by default. Probably you don't need to change this.
mqtt_discovery_prefix=homeassistant

# Polling interval in seconds
polling_interval=5

# This allows you to modify the amperage in case the inverter is giving an
# incorrect reading compared to measurement tools. Normally this will remain '1'
amperage_factor=1.0

# This allows you to modify the wattage in case the inverter is giving an
# incorrect reading compared to measurement tools. Normally this will remain '1'
watt_factor=1.0
